name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: BreCaspian
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/London

          # 1) Languages (indepth)
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: BreCaspian
          filename: github-metrics/languages.indepth.svg
          base: ""
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: lines, bytes
          plugin_languages_limit: 12
          config_timezone: Europe/London

      # 2) Issues & PRs (followup indepth)
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: BreCaspian
          filename: github-metrics/followup.indepth.svg
          base: ""
          plugin_followup: yes
          plugin_followup_indepth: yes
          config_timezone: Europe/London

      # 3) Featured repositories (pinned)
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: BreCaspian
          filename: github-metrics/repositories.pinned.svg
          base: ""
          plugin_repositories: yes
          plugin_repositories_pinned: 6   # 想展示几个就改这里
          config_timezone: Europe/London

      # 4) Coding habits + charts
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: BreCaspian
          filename: github-metrics/habits.charts.svg
          base: ""
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_days: 14
          plugin_habits_from: 200
          config_timezone: Europe/London
